backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Giant clock"
        name: "home"
      - file: "site/content/legal/privacy.md"
        label: "Privacy policy"
        name: "privacy"

